#!/bin/bash
DB=$1
BACKUP_FILE=$HOME/db_backups/$DB"-"`date '+%Y-%m-%d'`.sql
# BACKUP_FILE=$HOME/db_backup/$DB.sql
# echo Create $BACKUP_FILE ...
ignore=""
ignore_file=.$DB-ignore
if [ -f $ignore_file ]; then
        for TABLE in `cat $ignore_file`
        do :
                echo ingore $TABLE
                ignore+=" --ignore-table=$DB.$TABLE"
        done
fi
mysqldump --defaults-extra-file=$HOME/db_backups/.$DB --skip-lock-tables  $ignore $DB > $BACKUP_FILE
# echo Compressing \<br\/\>
gzip -f $BACKUP_FILE
